# Generated by Django 5.1.7 on 2025-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='chose',
            new_name='statuse',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtasks',
        ),
    ]
