# Generated by Django 5.1.7 on 2025-03-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0002_rename_chose_blog_statuse_remove_blog_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='statuse',
            new_name='status',
        ),
    ]
