# Generated by Django 5.1.7 on 2025-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0003_rename_statuse_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('not ready', 'Not Ready')], default='Not Ready', max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
