# Generated by Django 5.1.7 on 2025-03-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0004_subtask_status_subtask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtasks',
            field=models.ManyToManyField(to='kanbanapp.subtask'),
        ),
    ]
