# Generated by Django 5.1.7 on 2025-03-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0005_blog_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='columns',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
